version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/**"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: "America/Los_Angeles"
    
    # -----------------------------------------------------------
    # STABILITY POLICY: NO MAJOR UPDATES
    # -----------------------------------------------------------
    ignore:
      - dependency-name: "*" # Apply to ALL modules/providers
        update-types:
          - "version-update:semver-major"

    open-pull-requests-limit: 10
    
    groups:
       terraform-modules:
          patterns:
            - "*"
