# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    
    # Optional: Groups updates to keep things clean
    groups:
       terraform-modules:
          patterns:
            - "*"