version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    
    # -----------------------------------------------------------
    # SCHEDULE CONFIGURATION (New Feature as of 2025)
    # -----------------------------------------------------------
    schedule:
      interval: "cron"
      # Syntax: Minute Hour DayOfMonth Month DayOfWeek
      cron: "0 9 * * *"
      # ALWAYS set a timezone. Default is UTC, which might be 2am for you.
      timezone: "America/Los_Angeles"

    open-pull-requests-limit: 10
      
    groups:
       terraform-modules:
          patterns:
            - "*"



